import { NextApiRequest, NextApiResponse } from "next";

import { createServerSupabaseClient } from "@supabase/auth-helpers-nextjs";

export default async function createAvatar(req: NextApiRequest, res: NextApiResponse) {
  const supabase = createServerSupabaseClient({ req, res });

  const {
    data: { user }
  } = await supabase.auth.getUser();

  if (!user) {
    return res.status(401).json({ error: "Unauthorized" });
  }

  const { username, name, source } = req.body as {
    username: string;
    name: string;
    source: string;
  };

  const { data, error } = await supabase
    .from("avatars")
    .insert({
      id: username, // ID automatically generated by Supabase
      username,
      name,
      source,
      status: "requested",
      owner_id: user.id
    })
    .select("*")
    .single();

  if (error) {
    return res.status(500).json({ error: error.message });
  }

  return res.status(200).json(data);
}
